### PR TITLE
Fixes a bug where --open-url does not work

### PR DESCRIPTION
**Pull request by bomberstudios**
I was banging my head against the table because I couldn't get the `--open-url` to work, and it turned to be an easy fix

### CODE REVIEW

**Comment by awood** [comment]
@bomberstudios Thank you for the patch!

**Comment by bomberstudios** [comment]
Wow, that was fast, thanks : )

**Comment by bomberstudios** [comment]
Any chance to get a release with this fix? I'd like to bundle it on a project I'm working on : )

Thanks in advance!

**Comment by awood** [comment]
Just released Hawkins 2.0.4.  Sorry for the delay; I wanted to get in a fix I made to how Hawkins handles the thread communication.

**Comment by bomberstudios** [comment]
Awesome, thanks a lot : )

**Pull request merged**
